install! 'cocoapods',
  :preserve_pod_file_structure => true

use_frameworks!

platform :ios, '10.0'

target 'UnifiedForumParseFramework_Example' do
  pod 'UnifiedForumParseFramework', :path => '../'

  target 'UnifiedForumParseFramework_Tests' do
    inherit! :search_paths

    
  end
end
